### ISSUE TITLE
Looper documentation TODO list

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepspec#38]
Just keeping for myself a list of TODO things for looper docs update:

- [x] Howto: Run looper from PEPhub (this shows up in the hello world docs, but I think it maybe could be somewhere else?)
- [x] Combine 'Browsable HTML Reports' and 'Using pipestat'
- [x] Combine 'Concentric templates' with 'Looper variable namespaces' -- These are also related to "Running on a cluster with divvy" -- I need to explain the adapters, which goes along with the looper variable namespaces
- [x] "Pipeline tiers" probably belongs under "Running a pipeline", which should explain the difference between `looper run` and `looper runp`.
- [x] "Defining loper config" probably should come *after* "Defining a project".
